services:
  discord-search-bot-ui:
    image: ghcr.io/muni-town/discord-search-bot-ui:main
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      SEARCH_ENDPOINT: http://localhost:3001

  discord-search-bot:
    image: ghcr.io/muni-town/discord-search-bot:main
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      EMBEDDING_SERVICE: http://embedding-api:3000
      TOKEN: yourdiscordtoken
    volumes:
      - bot:/data

  embedding-api:
    image: ghcr.io/muni-town/embedding-api:main
    restart: unless-stopped
    ports:
      - 3000:3000

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage

volumes:
  qdrant:
  bot:
