[workspace]
authors = ["Zicklag <zicklag@katharostech.com>"]
channels = ["conda-forge"]
name = "semantic-search-api"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
ORT_LIB_LOCATION = "$PWD/ort/onnxruntime/lib"

[tasks]

[dependencies]
libstdcxx = ">=15.1.0,<16"
